In [33]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [34]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("/content/drive/MyDrive/car_evaluation.csv", header = None)
df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [35]:
# car evaluation 데이터셋 컬럼명 추가
df.columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "output"]

df

buying  maint  doors persons lug_boot safety output
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [36]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
output      0
dtype: int64

In [37]:
df['output'].value_counts()

output
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [38]:
# 'doors' 컬럼에서 '5more'을 5로 변경
df['doors'] = df['doors'].replace('5more', '5')

# 'persons' 컬럼에서 'more'을 5로 변경
df['persons'] = df['persons'].replace('more', '5')

# 'doors'와 'persons' 컬럼을 숫자로 변환
df['doors'] = df['doors'].astype(int)
df['persons'] = df['persons'].astype(int)

# 다시 Label Encoding 적용 (숫자로 변환한 'doors', 'persons' 제외)
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le  # 변환된 매핑 저장



In [40]:
df

buying  maint  doors  persons  lug_boot  safety  output
0          3      3      2        2         2       1       2
1          3      3      2        2         2       2       2
2          3      3      2        2         2       0       2
3          3      3      2        2         1       1       2
4          3      3      2        2         1       2       2
...      ...    ...    ...      ...       ...     ...     ...
1723       1      1      5        5         1       2       1
1724       1      1      5        5         1       0       3
1725       1      1      5        5         0       1       2
1726       1      1      5        5         0       2       1
1727       1      1      5        5         0       0       3

[1728 rows x 7 columns]

In [41]:
df['output'].value_counts()

output
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [49]:
# 'output'를 예측하기 위한 특성과 레이블 분리
X = df.drop('output', axis=1).values  # 특성 (X)
y = df['output'].values               # 레이블 (y)


In [51]:
X

array([[3, 3, 2, 2, 2, 1],
       [3, 3, 2, 2, 2, 2],
       [3, 3, 2, 2, 2, 0],
       ...,
       [1, 1, 5, 5, 0, 1],
       [1, 1, 5, 5, 0, 2],
       [1, 1, 5, 5, 0, 0]])

In [52]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [54]:
# 정규화
scaler = StandardScaler()
X = scaler.fit_transform(X)

# 데이터 나누기 (학습 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [55]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [57]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.9046242774566474
[[ 69   5   9   0]
 [  6   4   0   1]
 [ 10   0 225   0]
 [  2   0   0  15]]


In [58]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.661849710982659
[[ 13   0  66   4]
 [  2   0   9   0]
 [ 18   0 216   1]
 [ 12   0   5   0]]


In [59]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9682080924855492
[[ 76   6   1   0]
 [  1  10   0   0]
 [  0   0 235   0]
 [  1   2   0  14]]


In [62]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.9739884393063584
[[ 76   7   0   0]
 [  0  10   0   1]
 [  0   0 235   0]
 [  1   0   0  16]]
