In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats  # 과학용 계산 라이브러리
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import tensorflow as tf
from tensorflow import keras

In [32]:
df = pd.read_csv("https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/heart.csv", index_col=0)

# 특성과 레이블 분리
X = df.iloc[:, :-1]  # 마지막 열 제외한 특성
y = df.iloc[:, -1]   # 마지막 열(레이블)

# 학습용, 테스트용 데이터 분리 (8:2 비율)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
df

sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
age                                                                          
63     1   3       145   233    1        0      150      0      2.3      0   
37     1   2       130   250    0        1      187      0      3.5      0   
41     0   1       130   204    0        0      172      0      1.4      2   
56     1   1       120   236    0        1      178      0      0.8      2   
57     0   0       120   354    0        1      163      1      0.6      2   
..   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...   
57     0   0       140   241    0        1      123      1      0.2      1   
45     1   3       110   264    0        1      132      0      1.2      1   
68     1   0       144   193    1        1      141      0      3.4      1   
57     1   0       130   131    0        1      115      1      1.2      1   
57     0   1       130   236    0        0      174      0      0.0      1   

     ca  thal  target  
age                    
63    0     1       1  
37    0     2       1  
41    0     2       1  
56    0     2       1  
57    0     2       1  
..   ..   ...     ...  
57    0     3       0  
45    0     3       0  
68    2     3       0  
57    1     3       0  
57    1     2       0  

[303 rows x 13 columns]

In [34]:
# Decision Tree 모델
print("Decision Tree 코드")
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)
print("Decision Tree 결과: Accuracy =", accuracy_score(y_test, y_pred_dt))
print("\n", classification_report(y_test, y_pred_dt))
print("Confusion Matrix:")
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)

Decision Tree 코드
Decision Tree 결과: Accuracy = 0.8032786885245902

               precision    recall  f1-score   support

           0       0.77      0.83      0.80        29
           1       0.83      0.78      0.81        32

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

Confusion Matrix:
[[24  5]
 [ 7 25]]


In [35]:
# Logistic Regression 모델
print("Logistic Regression 코드")
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)
print("Logistic Regression 결과: Accuracy =", accuracy_score(y_test, y_pred_lr))
print("\n", classification_report(y_test, y_pred_lr))
print("Confusion Matrix:")
cm_lr = confusion_matrix(y_test, y_pred_lr)
print(cm_lr)

Logistic Regression 코드
Logistic Regression 결과: Accuracy = 0.8524590163934426

               precision    recall  f1-score   support

           0       0.83      0.86      0.85        29
           1       0.87      0.84      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

Confusion Matrix:
[[25  4]
 [ 5 27]]


In [38]:
# Support Vector Machine 모델
print("SVM 코드")
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
print("SVM 결과: Accuracy =", accuracy_score(y_test, y_pred_svm))
print("\n", classification_report(y_test, y_pred_svm))
print("Confusion Matrix:")
cm_svm = confusion_matrix(y_test, y_pred_svm)
print(cm_svm)

SVM 코드
SVM 결과: Accuracy = 0.7049180327868853

               precision    recall  f1-score   support

           0       0.79      0.52      0.62        29
           1       0.67      0.88      0.76        32

    accuracy                           0.70        61
   macro avg       0.73      0.70      0.69        61
weighted avg       0.73      0.70      0.69        61

Confusion Matrix:
[[15 14]
 [ 4 28]]


In [37]:
# Random Forest 모델
print("Random Forest 코드")
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)
print("Random Forest 결과: Accuracy =", accuracy_score(y_test, y_pred_rf))
print("\n", classification_report(y_test, y_pred_rf))
print("Confusion Matrix:")
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)

Random Forest 코드
Random Forest 결과: Accuracy = 0.8360655737704918

               precision    recall  f1-score   support

           0       0.83      0.83      0.83        29
           1       0.84      0.84      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

Confusion Matrix:
[[24  5]
 [ 5 27]]


In [39]:
# 정규화
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# KNN 모델 생성 및 학습
k = 3  # 최근접 이웃 개수
knn_model = KNeighborsClassifier(n_neighbors=k)
knn_model.fit(X_train_scaled, y_train)

# 예측 및 평가
y_pred_knn = knn_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred_knn)

print(f"KNN 결과: Accuracy = {accuracy:.4f}")
print("\n", classification_report(y_test, y_pred_knn))
print("Confusion Matrix:")
cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)

KNN 결과: Accuracy = 0.8689

               precision    recall  f1-score   support

           0       0.82      0.93      0.87        29
           1       0.93      0.81      0.87        32

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.88      0.87      0.87        61

Confusion Matrix:
[[27  2]
 [ 6 26]]
